PLAYER_CARD_CHANGE_LIMIT = 2
PLAYER_HAND_SIZE = 10

ABILITY_HORN_MULTIPLIER = 2
ABILITY_SCORCH_ROW_POWER = 10
ABILITY_SPY_DRAW = 2
ABILITY_BRINGER_OF_DEATH_DISCARD_AMOUNT = 2
ABILITY_BRINGER_OF_DEATH_DRAW_AMOUNT = 1
ABILITY_EMPEROR_LOOKUP_AMOUNT = 3

DECK_SPECIAL_CARD_LIMIT = 11
DECK_UNIT_CARD_AMOUNT = 30
